name: Ubuntu Server

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Install Go protobuf
        run: |
          cd server
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Build server
        run: |
          cd server
          go mod tidy
          go build -o server.out .
